name: Build project

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run:
        dotnet build SievesProject --configuration Release
        # dir
